account/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from . import views

app_name = 'account'

urlpatterns = [
    path('', views.home, name='home'),
    path('signUp/', views.signUp, name='signUp'),
    path('signIn/', views.signIn, name='signIn'),
    path('signOut/', views.signOut, name='signOut'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detalhe, name='cart_detalhe'),
    path('adicionar/<int:produto_id>', views.cart_adicionar, name='cart_adicionar'),
    path('remover/<int:produto_id>', views.cart_remover, name='cart_remover'),   
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.produto_list, name='produto_list'),
    path('<slug:categoria_slug>/', views.produto_list, name='produto_list_por_categoria'),
    path('<int:id>/<slug:slug>/', views.produto_detalhe, name='produto_detalhe'),  # Correção feita aqui
]

virtualshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    genero = models.CharField(max_length=20, null=True, choices=(('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Outros')))
    nasimento = models.DateField(null=True, blank=True)
    redesocial = models.CharField(max_length=100, null=True, blank=True)
    
    def __str__(self):
        return self.username

cart/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Categoria(models.Model):
    nome = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ['nome']
        indexes = [
            models.Index(fields=['nome']),
        ]
        verbose_name = 'categoria'
        verbose_name_plural = 'categorias'

    def __str__(self):
        return self.nome
    
    def get_absolute_url(self):
        return reverse(
            'shop:produto_list_por_categoria', args=[self.slug]
        )

class Produto(models.Model):
    categoria = models.ForeignKey(
        Categoria,
        related_name='produtos',
        on_delete=models.CASCADE
    )
    nome=models.CharField(max_length=200)
    slug=models.SlugField(max_length=200)
    imagem=models.ImageField(
        upload_to='produtos/%Y/%m/%d',
        blank=True
    )
    descricao=models.TextField(blank=True)
    preco=models.DecimalField(max_digits=10, decimal_places=2)
    disponivel=models.BooleanField(default=True)
    criado=models.DateTimeField(auto_now_add=True)
    atualizado=models.DateTimeField(auto_now=True)

    class Meta:
        ordering=['nome']
        indexes=[
            models.Index(fields=['id','slug']),
            models.Index(fields=['nome']),
            models.Index(fields=['-criado']),
        ]

    def __str__(self):
        return self.nome
    
    def get_absolute_url(self):
        return reverse(
            'shop:produto_detalhe', args=[self.id, self.slug]
        )

cart/forms.py
from django import forms


PRODUTO_QUANTIDADE_CHOICES = [(i, str(i)) for i in range (1,10)]

class CartAddQuantityForm(forms.Form):
    quantidade = forms.TypedChoiceField(
        choices=PRODUTO_QUANTIDADE_CHOICES,
        coerce=int
    )
    override = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput
    )
    

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model, authenticate, login, logout
from django.http import HttpResponse

# Create your views here.
def signUp(request):
    User = get_user_model()
    
    if request.user.is_authenticated:
        return render(request=request, template_name='account/home.html')
    
    if request.method == 'POST':
        #intercepta os dados do formulario/ as variaveis transacionadas no POST
        username = request.POST.get('username','')
        email = request.POST.get('email','')
        password = request.POST.get('password','')
        genero = request.POST.get('genero','')
        nasimento = request.POST.get('nasimento','')
        redesocial = request.POST.get('redesocial','')
        
        #criando o objeto do usuario com as variaveis de instancia
        user = User.objects.create_user(username=username, 
                                        email=email, 
                                        password=password, 
                                        genero=genero, 
                                        nasimento=nasimento, 
                                        redesocial=redesocial)
        
        #redirecinando o usuario para a pagina home
        user = authenticate(username=username, password=password)
        
        if user is not None:
            login(request, user)
        return redirect('/')
        
    return render(request=request, template_name='account/signup.html', context={})

def signIn(request):
    if request.method == 'POST':
        #intercepta os dados do formulario/ as variaveis transacionadas no POST
        username = request.POST.get('username','')
        password = request.POST.get('password','')
        
        user = authenticate(username=username, password=password)
        
        if user is not None:
            login(request, user)
            request.session['username'] = username
            request.session.save()
            return redirect('/')
        else:
            return HttpResponse('Autenticação falhou!')
          
    return render(request=request, template_name='account/signin.html', context={})

def home(request):
    return render(request=request, template_name='account/home.html', context={})

def signOut(request):
    if request.user.is_authenticated:
        logout(request)
        return redirect('/')

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from shop.models import Produto
from django.views.decorators.http import require_POST
# Create your views here.
from  .forms import CartAddQuantityForm
from .cart import Cart

@require_POST
def cart_adicionar(request, produto_id):
    cart = Cart(request)
    produto = get_object_or_404(Produto, id= produto_id)
    form = CartAddQuantityForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            produto=produto,
            quantidade=cd['quantidade'],
            #override_quantity=cd['override'],
        )
    return redirect('cart:cart_detalhe')

def cart_detalhe(request):
    cart = Cart(request)
    for item in cart:
        item['atualizar_quantidade_form'] = CartAddQuantityForm(
            initial={'quantidade' : item['quantidade'], 'override': True}
        )
    return render(request, 'cart/detalhe.html', {'cart' : cart})

@require_POST
def cart_remover(request, produto_id):
    cart = Cart(request)
    produto = get_object_or_404(Produto, id=produto_id)
    cart.remove(produto)
    return redirect('cart:cart_detalhe')

shop/views.py
from django.shortcuts import get_object_or_404, render
from .models import Categoria, Produto
from cart.forms import CartAddQuantityForm


def produto_list(request, categoria_slug=None):
    categoria = None
    categorias = Categoria.objects.all()
    produtos = Produto.objects.filter(disponivel=True)
    if categoria_slug:
        categoria = get_object_or_404(Categoria, slug=categoria_slug)
        produtos = produtos.filter(categoria=categoria)
    return render(
        request,
        'shop/produto/list.html',
        {
            'categoria':categoria,
            'categorias':categorias,
            'produtos':produtos
        }
    )

def produto_detalhe(request, id, slug):
    produto = get_object_or_404(
        Produto, id=id, slug=slug, disponivel=True
    )
    cart_produto_form = CartAddQuantityForm()
    return render( 
        request, 
        'shop/produto/detail.html',
        {
            'produto':produto, 'cart_produto_form':cart_produto_form
        }
    )

cart/templates/cart/detalhe.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
Carrinho de Compras
{% endblock %}

{% block content %}
  <h1>Carrinho de Compras</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>Imagem</th>
        <th>Produto</th>
        <th></th>
        <th>Remover</th>
        <th>Preço Unitário</th>
        <th>Preço</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with produto=item.produto %}
          <tr>
            <td>
              <a href="{{ produto.get_absolute_url }}">
                <img src="{% if produto.imagem %}{{ produto.imagem.url }}
                {% else %}{% static "img/no_image.png" %}{% endif %}">
              </a>
            </td>
            <td>{{ produto.nome }}</td>
            <td>
              <form action="{% url "cart:cart_adicionar" produto.id %}" method="post">
                {{ item.atualizar_quantidade_form.quantidade }}
                {{ item.atualizar_quantidade_form.override }}
                <input type="submit" value="Update">
                {% csrf_token %}
              </form>
            </td>
            <td>
              <form action="{% url "cart:cart_remover" produto.id %}" method="post">
                <input type="submit" value="Remove">
                {% csrf_token %}
              </form>
            </td>
            <td class="num">${{ item.preco }}</td>
            <td class="num">${{ item.preco_total }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr class="total">
        <td>Total</td>
        <td colspan="4"></td>
        <td class="num">${{ cart.get_preco_total }}</td>
      </tr>
    </tbody>
  </table>
  <p class="text-right">
    <a href="{% url "shop:produto_list" %}" class="button
    light">Continuar comprando</a>
    <a href="#" class="button">Checkout</a>
  </p>
{% endblock %}

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>{% block title %}VirtualShop{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'shop/css/base.css' %}">
  </head>
  <body>
    <div id="header">
      <a href="/" class="logo">VirtualShop</a>
    </div>
    <div id="subheader">
      <div class="cart">
        {% with total_items=cart|length %}
          {% if total_items > 0 %}
            Seu carrinho:
            <a href="{% url 'cart:cart_detalhe' %}">
              {{ total_items }} item{{ total_items|pluralize }},
              ${{ cart.get_total_price }}
            </a>
          {% elif not order %}
            Seu carrinho está vázio.
          {% endif %}
        {% endwith %}
      </div>
    </div>
    <div id="content">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

shop/templates/shop/produto/detail.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}
  {{ produto.nome }}
{% endblock %}
{% block content %}
  <div class="product-detail">
    <img src="{% if produto.imagem %}{{ produto.imagem.url }}{% else %}
    {% static 'img/no_image.png' %}{% endif %}">
    <h1>{{ produto.nome }}</h1>
    <h2>
      <a href="{{ produto.categoria.get_absolute_url }}">
        {{ produto.categoria }}
      </a>
    </h2>
    <p class="price">${{ produto.preco }}</p>
    <form action="{% url 'cart:cart_adicionar' produto.id %}" method="post">
      {{ cart_produto_form }}
      {% csrf_token %}
      <input type="submit" value="Adicionar ao Carrinho">
    </form>
    {{ produto.descricao|linebreaks }}
  </div>
{% endblock %}

shop/templates/shop/produto/list.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}
  {% if categoria %}{{ categoria.name }}{% else %}Listagem de Produtos{% endif %}
{% endblock %}

{% block content %}
  <div id="sidebar">
    <h3>Categorias</h3>
    <ul>
      <li {% if not categoria %}class="selected"{% endif %}>
        <a href="{% url 'shop:produto_list' %}">Todas</a>
      </li>
      {% for c in categorias %}
        <li {% if categoria.slug == c.slug %}class="selected"{% endif %}>
          <a href="{{ c.get_absolute_url }}">{{ c.nome }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
  <div id="main" class="product-list">
    <h1>{% if categoria %}{{ categoria.nome }}{% else %}Produtos{% endif %}</h1>
     {% for produto in produtos %}
      <div class="item">
        <a href="{{ produto.get_absolute_url }}">
          <img src="{% if produto.imagem %}{{ produto.imagem.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
        </a>
        <a href="{{ produto.get_absolute_url }}">{{ produto.nome }}</a>
        <br>
        ${{ produto.preco }}
      </div>
    {% endfor %}
  </div>
{% endblock %}